# Generated by Django 3.2 on 2023-06-05 20:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=300)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('comment_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_location', models.CharField(default='Mombasa', max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('product_condition', models.CharField(choices=[('New', 'NEW'), ('Well used', 'WELL_USED'), ('Used', 'USED'), ('Scrap', 'SCRAP')], default='New', max_length=50)),
                ('post_type', models.CharField(choices=[('Sell', 'SELL'), ('Swap', 'SWAP')], default='Sell', max_length=50)),
                ('about', models.CharField(max_length=100)),
                ('sell_price', models.IntegerField(default=0)),
                ('gold_price', models.IntegerField(default=0)),
                ('product_pick_up', models.CharField(choices=[('Meetup', 'MEETUP'), ('On Premise', 'ON_PREMISE')], default='Meetup', max_length=50)),
                ('payment_method', models.CharField(choices=[('Mpesa ', 'MPESA'), ('Cash', 'CASH')], default='Mpesa ', max_length=50)),
                ('posted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posted_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='RePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('original_post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='original_post', to='posts.post')),
                ('reposted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_repost', to='accounts.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=300)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('related_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_comment_reply', to='posts.comment')),
                ('reply_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply_by', to='accounts.profile')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_name', models.CharField(max_length=255, null=True)),
                ('image', models.ImageField(upload_to='images/')),
                ('default', models.BooleanField(default=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='for_product', to='posts.post')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_likes', to='posts.post')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_likes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='related_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_comment', to='posts.post'),
        ),
    ]
