# Generated by Django 3.2 on 2023-05-17 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='product',
            new_name='post',
        ),
    ]
