# Generated by Django 3.2 on 2023-09-01 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='topic',
            field=models.CharField(choices=[('general', 'General'), ('technology', 'Technology'), ('culture', 'Culture'), ('faith & religion', 'Faith & Religion'), ('politics', 'Politics'), ('sports', 'Sports')], default='general', max_length=50),
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
