# Generated by Django 3.2 on 2023-06-05 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='sell_price',
            new_name='sale_price',
        ),
    ]
