# Generated by Django 3.2 on 2023-05-27 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Swap',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='posts.post')),
                ('about', models.CharField(max_length=300)),
                ('swap_pick_up', models.CharField(choices=[('Meetup', 'MEETUP'), ('On Premise', 'ON_PREMISE'), ('delivery', 'DELIVERY')], default='Meetup', max_length=50)),
                ('swap_condition', models.CharField(choices=[('New', 'NEW'), ('Well used', 'WELL_USED'), ('Used', 'USED'), ('Scrap', 'SCRAP')], default='New', max_length=50)),
            ],
            bases=('posts.post',),
        ),
        migrations.RemoveField(
            model_name='story',
            name='post_ptr',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='Story',
        ),
    ]
