# Generated by Django 3.2 on 2023-09-05 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='topic',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('cars', 'Cars'), ('motorbikes', 'Motorbikes'), ('bicycles', 'Bicycles'), ('fashion', 'Fashion'), ('gigs', 'Gigs'), ('jobs', 'Jobs'), ('electronics', 'Electronics'), ('accessories', 'Accessories'), ('art', 'Art'), ('luxury', 'Luxury'), ('real estate', 'REAL_ESTATE'), ('food and drinks', 'FOOD_DRINKS'), ('health and beauty', 'Health and Beauty'), ('furniture', 'Furniture')], default='cars', max_length=50),
        ),
    ]
