# Generated by Django 3.2 on 2023-08-04 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_remove_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='moderation',
        ),
    ]
