# Generated by Django 3.2 on 2023-09-05 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20230905_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_image',
        ),
        migrations.AddField(
            model_name='post',
            name='listing_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('cars', 'Cars'), ('motorbikes', 'Motorbikes'), ('bicycles', 'Bicycles'), ('fashion', 'Fashion'), ('gigs', 'Gigs'), ('jobs', 'Jobs'), ('electronics', 'Electronics'), ('accessories', 'Accessories'), ('art', 'Art'), ('luxury', 'Luxury'), ('real estate', 'Real Estate'), ('food and drinks', 'Food and Drinks'), ('beauty and fitness', 'Beauty and Fitness'), ('furniture', 'Furniture')], default='cars', max_length=50),
        ),
    ]
