# Generated by Django 3.2 on 2023-09-13 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20230905_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('cars', 'Cars'), ('motorbikes', 'Motorbikes'), ('bicycles', 'Bicycles'), ('fashion', 'Fashion'), ('gigs', 'Gigs'), ('hiring', 'Hiring'), ('electronics', 'Electronics'), ('accessories', 'Accessories'), ('art', 'Art'), ('luxury', 'Luxury'), ('real estate', 'Real Estate'), ('food and drinks', 'Food and Drinks'), ('beauty and fitness', 'Beauty and Fitness'), ('furniture', 'Furniture')], default='cars', max_length=50),
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_image', to='posts.post')),
            ],
        ),
    ]
