# Generated by Django 3.2 on 2023-09-14 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_postimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.AddField(
            model_name='post',
            name='topic',
            field=models.CharField(choices=[('general', 'General'), ('science_technology', 'Science & Technology'), ('culture', 'Culture'), ('faith_religion', 'Faith & Religion'), ('politics', 'Politics'), ('sports', 'Sports'), ('business_finance', 'Business & Finance'), ('news', 'News'), ('music', 'Music'), ('history', 'History'), ('philosophy', 'Philosophy'), ('fiction', 'Fiction'), ('health_wellness', 'Health & Wellness'), ('art', 'Art'), ('design', 'Design'), ('education', 'Education'), ('humour', 'Humour'), ('literature', 'Literature')], default='general', max_length=50),
        ),
        migrations.DeleteModel(
            name='PostImage',
        ),
    ]
