# Generated by Django 3.2 on 2023-08-07 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_post_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='label',
        ),
    ]
