# Generated by Django 3.2 on 2023-09-14 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_rename_image_post_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='headline',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
