# Generated by Django 3.2 on 2023-09-14 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_alter_post_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='topic',
            field=models.CharField(choices=[('general', 'General'), ('science & technology', 'Science & Technology'), ('culture', 'Culture'), ('faith & religion', 'Faith & Religion'), ('politics', 'Politics'), ('sports', 'Sports'), ('business & finance', 'Business & Finance'), ('news', 'News'), ('music', 'Music'), ('history', 'History'), ('philosophy', 'Philosophy'), ('fiction', 'Fiction'), ('health & wellness', 'Health & Wellness'), ('art', 'Art'), ('design', 'Design'), ('education', 'Education'), ('humour', 'Humour'), ('literature', 'Literature')], default='general', max_length=50),
        ),
    ]
