# Generated by Django 3.2 on 2023-09-15 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_remove_post_headline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='topic',
            field=models.CharField(choices=[('general', 'General'), ('science & technology', 'Science & Technology'), ('culture', 'Culture'), ('faith & religion', 'Faith & Religion'), ('politics', 'Politics'), ('sports', 'Sports'), ('business & finance', 'Business & Finance'), ('news', 'News'), ('music', 'Music'), ('history', 'History'), ('philosophy', 'Philosophy'), ('health & wellness', 'Health & Wellness'), ('art & design', 'Art & Design')], default='general', max_length=50),
        ),
    ]
