# Generated by Django 3.2 on 2023-09-08 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20230908_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='profile_pics/default_avatar.jpg', null=True, upload_to='profile_pics/'),
        ),
    ]
