# Generated by Django 3.2 on 2023-05-26 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=20)),
                ('story', models.CharField(max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('thread_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thread_by', to='accounts.profile')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ThreadComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_image', models.ImageField(upload_to='images/')),
                ('comment', models.CharField(max_length=300)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('comment_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commented_by', to='accounts.profile')),
                ('related_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thread_comment', to='chats.thread')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ThreadFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ThreadReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_image', models.ImageField(upload_to='images/')),
                ('comment', models.CharField(max_length=300)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('related_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thread_comment_reply', to='chats.threadcomment')),
                ('reply_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replied_by', to='accounts.profile')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ThreadLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thread_likes', to='chats.thread')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_thread_likes', to='accounts.profile')),
            ],
        ),
        migrations.CreateModel(
            name='ThreadImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_name', models.CharField(max_length=255, null=True)),
                ('image', models.ImageField(upload_to='images/')),
                ('default', models.BooleanField(default=False)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='for_thread', to='chats.thread')),
            ],
        ),
        migrations.CreateModel(
            name='ReThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('original_thread', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='original_thread', to='chats.thread')),
                ('rethread_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_rethread', to='accounts.profile')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
